framework: torch
wrapper:
  shuffle: True
  batch_size: 1024
  L_FP: 1
  L_FN: 1 
model:
  type: mlp
  input_dim: 12
  hidden_dims: [128]
  output_dim: 2
  num_layers: 1
  dropout: 0.0
train:
  lr: 1.0e-3
  weight_decay: 1.0e-5
  device: cpu
  epochs: 3
  save_path: 'saves/mlp.pkl'
  save_freq: 5
