framework: torch
wrapper:
  shuffle: True
  batch_size: 4
model:
  type: mlp
  input_dim: 6
  hidden_dims: [64,128,64]
  output_dim: 1
  num_layers: 3
  dropout: 0.0
train:
  lr: 1.0e-3
  weight_decay: 1.0e-5
  device: cpu
  epochs: 3
  save_path: 'saves/mlp.pkl'
  save_freq: 5