framework: torch
wrapper:
  shuffle: True
  batch_size: 512
  L_FP: 1
  L_FN: 1 
model:
  type: mlp
  input_dim: 12
  hidden_dims: [64, 64, 16]
  output_dim: 2
  dropout: 0.0
train:
  lr: 1.0e-3
  weight_decay: 1.0e-6
  device: cuda #cuda | cpu
  epochs: 100
  save_freq: 5
